Tidy up the start of the using draupnir page.
MTRNord/draupnir4all_docs pull request #1
Opened 2023-08-29 19:15 UTC by Gnuxie

Formalize and clarify some of the language, and remove some ambiguities.

Just a general tidy up really.

2023-08-29 19:15 UTC, Gnuxie commented on content/docs/how_to_use_draupnir.md
> +{{/* FIXME: why are we doing this? doesn't d4all create them a list called `list`? */}}
This is a problem.

2023-08-30 10:37 UTC, MTRNord commented on content/docs/how_to_use_draupnir.md
> +{{/* FIXME: why are we doing this? doesn't d4all create them a list called `list`? */}}
I guess then we should omit it or say its for additional lists? :thinking:

2023-08-30 10:37 UTC, MTRNord requested changes
meow meow (see your comment)

2023-09-07 09:23 UTC, MTRNord approved these changes
LGTM

2023-09-07 09:24 UTC, merged